version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
